### ISSUE TITLE
Determine if readthedocs and local doc generation requires having extra files

### ISSUE THREAD

**Issue by cdw** [AllenCellModeling/cookiecutter-pypackage#18]
Just what is says in the title

**Comment by JacksonMaxfield** [comment]
This has been fixed already in [the most recent version](https://raw.githubusercontent.com/AllenCellModeling/cookiecutter-pypackage/master/{{cookiecutter.project_slug}}/README.rst).

I think the project you found this on may just have been initialized with an older version of cookiecutter.

That said, I know you have a desire to cut a lot of the extra files in this repo and I think the production version of [`t4distribute`](https://github.com/AllenCellModeling/t4distribute) is a good example of my set of minimal files. Specifically, `t4distribute` drops any documentation files, so `MANIFEST`, and `AUTHORS.rst` for example. As well as switches the readme to markdown instead of rst. Thoughts on that going into cookiecutter?

**Comment by cdw** [comment]
I'd love to see the removal of `MANIFEST` and the like. My recollection was that we were wedded to rst if we wanted to use auto-generation of docstring-based documentation with Napoleon. Is that not the case?

**Comment by JacksonMaxfield** [comment]
For local doc generation I think it may fail. But the readthedocs integrated github repo generated docs I think it will be fine? Not entirely sure.

**Comment by cdw** [comment]
The former is easy to test, at least. Maybe move doing that to an enhancement for whenever there is more time? I'll guinea pig it if I get the chance.

**Comment by JacksonMaxfield** [comment]
Changed the name because the initial issue was resolved but a new issue is needed to be investigate :^)
