### ISSUE TITLE
Should `make clean` delete `.tox/`?

### ISSUE THREAD

**Issue by cdw** [AllenCellModeling/cookiecutter-pypackage#21]
Currently `make clean` doesn't delete the `.tox/` dir that is created when running tox locally. The nice part of this is that the tox environment persists even when you `make clean` which makes tox faster to run. The not-nice part of this is that it pollutes within-project searches with results from the virtual env. 

I propose we change to `make clean` removing `.tox/` but am interested in other views.

**Comment by JacksonMaxfield** [comment]
I am a bit confused why yours doesn't? It should be cleaning the `tox` dir every time it runs as that is one of the primary reasons for the clean. The makefile does have it already as seen [here](https://github.com/AllenCellModeling/cookiecutter-pypackage/blob/master/{{cookiecutter.project_slug}}/Makefile#L48).

I know on my home machine I have to run `sudo make clean` to get it to work fully... Maybe that is the issue here?

**Comment by cdw** [comment]
Huh... that line was missing from mine. That must be a modification on my part. Thanks! ¯\_(ツ)_/¯
